# -*- coding: utf-8 -*-
# Part of Contagra. See LICENSE file for full copyright and licensing details.

{
    'name': 'Agri',
    'summary': 'Agriculture base module',
    'website': 'https://github.com/contagra/odoo-agri',
    'category': 'Operations/Inventory',
    'version': '0.2.6',
    'sequence': 1,
    'author': 'Contagra',
    'license': 'Other proprietary',
    'description': 'Agriculture base module',
    'depends': [
        'base',
        'date_range',
        'product',
        'stock',
        'uom',
    ],
    'data': [
        'security/agri_security.xml',
        'security/ir.model.access.csv',
        'data/uom_data.xml',
        'data/product_data.xml',
        'data/product.category.csv',
        # 'data/agri.budget.template.csv',
        # 'data/agri.budget.template.line.csv',
        'data/agri_crop_data.xml',
        'data/agri_irrigation_data.xml',
        'data/agri.land.use.csv',
        'data/agri_soil_data.xml',
        'data/agri_terrain_data.xml',
        'data/decimal_precision_data.xml',
        'data/water_source.xml',
        'data/agri.active.ingredient.csv',
        'data/agri.nutrient.csv',
        'data/agri.pest.disease.csv',
        'data/res_company_data.xml',
        'data/res_country_data.xml',
        'views/date_range_views.xml',
        'views/ir_attachment_views.xml',
        # 'views/product_template_views.xml',
        'views/product_views.xml',
        'views/res_config_settings_views.xml',
        'views/agri_enterprise_views.xml',
        'views/agri_active_ingredient_views.xml',
        'views/agri_nutrient_views.xml',
        'views/agri_pest_disease_views.xml',
        'views/agri_product_views.xml',
        'views/uom_views.xml',
        'views/menus.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'assets': {
        'web.assets_frontend': [
            'agri/static/src/js/agri_form_validation.js',
            'agri/static/src/js/agri_portal_sidebar.js',
        ],

    }
}
